testing quality gate

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,6 +27,16 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+      - name: Check SonarQube Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
+        run: |
+          status=$(curl -s -u $SONAR_TOKEN: ${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=asongent_DevSecOps_AYmIrA13R_yVDtItJUdo | jq -r '.projectStatus.status')
+          if [ "$status" != "OK" ]; then
+            echo "SonarQube Quality Gate check failed"
+            exit 1
+          fi
   #       - name: SonarQube Scan
 #         uses: kitabisa/sonarqube-action@v1.2.0
 #         with:
